travis:
  secure:
    BINSTAR_TOKEN: ERd2Bm/dm6Ch9YfjCWioBtuSnOl4Jfa2rHVRv23dSwt1sexC8GYSJuGTPjlPB3Wl9/3AxhVMPIcvSrPj9pirBcmKF3+rWageTaE/9NISQCjRJY1xpjd4EWcXCMcYCZaGONRYYSJKc/WgFjjC6w8HncmNa4Dd/CMgPxXwBTvQsgnroUdhVExD77TQYwQEl2RbPBHlvJjSr6ctgxiF1oX+D/eC+B4gaN0jo7PIYQPys1K3OqjWZ/5mcYfuQmEOXNU6EYVYZDmtb7IJ6J76vCEHTP1ZOCEBFdINKh4Oh2ehMGCHtc/JBXZ9pryOL9mfi5G6qUA53N8gPZfy5PMPOmXBcQCxkJK9KE3vDNO/C3GTSNBxQU56x5pG/h3dM27NZqyZaEMmqHndQhkJ34uc88kmOofg4IJVCZb1PC3NRJj8Q7ssV3igSMqHnN1DbX4Jb99KqWnDJCGkwOPQOWuAxY0rI3L7aEN6QmfPPIJe/aWBKsIMK/MmQ3lGDRoBNpVvIN11TZchJug23eqHcdLLVKAVWMQxkOCpzJCD7jjuz45NzyKkPMICwnJDhFDqsdVGDoIXU4ahdCXEGIp/kGwGs5cMbFjrF9H1JXTqwS/skQhIZLQcdT1x4UbowvVNs9y9EKqmCmJqmAyZbS7oWJA5phG99A0iHNMECDmOPZB13svOiL0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
