travis:
  secure:
    BINSTAR_TOKEN: lWBR65Jd99gZZIP7DOL2PuHAX5DaqBiDOYR7GzL1ReM06Zjc25L+RBfW3cXsuTSFgzrLFP9eKpmQF3E4Gg3sUZjZ7qlPofhLm8LJ8Ag/wiKv/ELy2n+xyx8IXeWSXBfCbNGNxgQ7hNriAlUHdAGvyNuZXkm+gHgyR0PBie7ko/qeM8mRqn8pcGARG11O5rSSWuCOMt3M9JHqh0ZEEApNmHYoIh2tlggLUiloFWYi0yJneH2LUuGJpLoFgIUpCGATyUmwCYDcLg9YZQRTHv9gPdnzx0RZq++TYdiWECOKP3fADIL/iy9/uHs7MyCInmUrhsVpKu4FRi+mMmXpylFIGevsD7FEE1iaA3/gIE1heznyye+F3dzA36GxWfsbg4Fc4Eht5zsxhnSLoQ+MXfDul5KG22OBlat00B3nNZ1JVIDeQzr4zOe/OYXgEO+YBPi+Nis4Q+n3b/Eq/ivZtl9YYY53GRXgkh0I4eF+V1GPPLy8+Kua6ap+XlPoeYTiWdcurLOA0U1vBRdpMMi7W7/RGCDOqNqxjEJyBhcwLoKJjbYojJ7fnUjEriSTzDjxbYpvxUzMo2cdZLfwABor/o40jY4sxtLcYUey/iQpQK9RINknJx90yI1SaAvlR4dJI3zizc8XFxh6MSLhpvFcUBvjZb1G+oF7skywTD/IsVPsd+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
